neighborlist_cutoff: &neighborlist_cutoff 5.0
architecture: "alchemical_model"

datamodule:
  train_frames_path: "path/to/train_frames.xyz"
  val_frames_path: "path/to/val_frames.xyz"
  batch_size: 16
  neighborlist_cutoff_radius: *neighborlist_cutoff
  target_properties: ["energies", "forces"]
  shuffle: true

litmodel:
  restart: false
  energies_weight: 1.0
  forces_weight: 10.0
  lr: 1e-3
  weight_decay: 1e-5

model:
  hidden_sizes: [64, 64, 64]
  contract_center_species: true
  output_size: 1
  cutoff: *neighborlist_cutoff
  basis_cutoff_power_spectrum: 400
  radial_basis_type: "physical"
  trainable_basis: true
  num_pseudo_species: 4

trainer:
  max_epochs: 1000
  accelerator: "gpu"
  early_stopping_callback:
    monitor: "val_energies_mae"
    patience: 50
    mode: "min"
  checkpoint_callback:
    monitor: "val_energies_mae"
    filename: "best_model.pl"
    save_top_k: 1
    mode: "min"

logging:
  project: "alchemical_learning"
  name: "am_contract_center_species"
  save_dir: "./logs"
  log_model: true



