neighborlist_cutoff: &neighborlist_cutoff 5.0

datamodule:
  frames_path: "../data/hea_samples_bulk.xyz"
  train_val_test: [0.8, 0.1, 0.1]
  batch_size: 16
  neighborlist_cutoff_radius: *neighborlist_cutoff
  target_properties: ["energies", "forces"]
  shuffle: True

litmodel:
  restart: false
  energies_weight: 1.0
  forces_weight: 1.0
  lr: 1e-3
  weight_decay: 1e-5

model:
  hidden_sizes: [64, 64]
  output_size: 1
  cutoff: *neighborlist_cutoff
  basis_cutoff_radial_spectrum: 100
  basis_cutoff_power_spectrum: 50
  num_pseudo_species: 4
  device: "cpu"

trainer:
  max_epochs: 100
  early_stopping_callback:
    monitor: "loss"
    patience: 50
    mode: "min"
  checkpoint_callback:
    monitor: "val_energies_mae"
    filename: "best_model.pl"
    save_top_k: 1
    mode: "min"



